name: zeiterfassung_v1
description: A new Flutter project.
publish_to: 'none' # Prevents accidental publishing
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  hive_generator: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
